### ISSUE TITLE
Skyrim SE Installer Fails

### ISSUE THREAD

**Issue by BobbyBeeblebrox** [rockerbacon/lutris-skyrimse-installers#249] opened 2021-10-28 19:37 UTC
Hello all, I'm getting an error when the installer updates winetricks. Downloaded the latest vcrun files (bothx86 and x64) and still no change to the error. I had MO2 installed and working perfectly with 150+mods prior to latest Lutris update.  I uninstalled SSE and MO2 in order to make space to test some other applications and since latest Lutris update, cannot re-install.  Thanks very much in advance for taking the time.
SysInfo:
[System]
OS:              Pop!_OS 21.04 hirsute
Arch:            x86_64
Kernel:          5.13.0-7614-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Phenom(tm) II X4 965 Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon (TM) R9 Fury Series (FIJI, DRM 3.41.0, 5.13.0-7614-generic, LLVM 12.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.2
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.2
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.2
Vulkan:          Supported

Here is my log:

2021-10-28 12:26:05,485: Starting Lutris 0.5.9
2021-10-28 12:26:05,543: No cores found
2021-10-28 12:26:06,571: Startup complete
2021-10-28 12:26:06,574: Running AMD Mesa driver 21.2.2 on AMD Radeon (TM) R9 Fury Series (FIJI, DRM 3.41.0, 5.13.0-7614-generic, LLVM 12.0.0) (0x7300)
2021-10-28 12:26:06,575: GPU: 1002:7300 1682:970A (amdgpu drivers)
2021-10-28 12:26:14,119: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/dialog/dialog.sh, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/dialog
2021-10-28 12:26:14,122: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/find_library_for_appid/find-library-for-appid.sh, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/find_library_for_appid
2021-10-28 12:26:14,125: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/gamesinfo/gamesinfo.tar.gz, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/gamesinfo
2021-10-28 12:26:14,128: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/proton_launcher/proton-launcher.sh, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/proton_launcher
2021-10-28 12:26:14,131: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/wine_launcher/wine-launcher.sh, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/wine_launcher
2021-10-28 12:26:14,134: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/nxm_broker/modorganizer2-nxm-broker.sh, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/nxm_broker
2021-10-28 12:26:14,137: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/nxm_mime_handler/modorganizer2-nxm-handler.desktop, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/nxm_mime_handler
2021-10-28 12:26:14,140: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/openjdk
2021-10-28 12:26:14,143: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/fose/fose_v1_2_beta2.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/fose
2021-10-28 12:26:14,145: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/f4se/f4se_0_06_21.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/f4se
2021-10-28 12:26:14,148: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/nvse/nvse_5_1_beta4.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/nvse
2021-10-28 12:26:14,150: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/mwse/mwse.zip, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/mwse
2021-10-28 12:26:14,151: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/obse/obse_0021.zip, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/obse
2021-10-28 12:26:14,152: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/skse/skse_1_07_03.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/skse
2021-10-28 12:26:14,153: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/skse64/skse64_2_00_17.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/skse64
2021-10-28 12:26:14,154: All files available
2021-10-28 12:26:14,154: All files are available, continuing install
2021-10-28 12:26:14,157: Skipping caching of /home/bobby/Downloads/MO2/mod-organizer-2/mo_archive/Mod.Organizer-2.2.2.1.7z, already cached in /home/bobby/Downloads/MO2/mod-organizer-2/mo_archive
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:493: Warning: ../../../gobject/gsignal.c:2732: instance '0x1e38500' has no handler with id '5684'
  return func(*args, **kwargs)
Started initial process 44781 from /usr/bin/bash -c xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 37319384 bytes (36 MiB)                             

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/openjdk/OpenJDK8U-jre_x64_windows_8u252b09.zip
Type = zip
Physical Size = 37319384

Everything is Ok                                    

Folders: 15
Files: 121
Size:       94859720
Compressed: 37319384

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 384875 bytes (376 KiB)                           

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/fose/fose_v1_2_beta2.7z
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/fose/fose_v1_2_beta2.7z
Type = 7z
Physical Size = 384875
Headers Size = 3155
Method = LZMA:6m BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 8
Files: 184
Size:       4753751
Compressed: 384875

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 598435 bytes (585 KiB)                           

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/f4se/f4se_0_06_21.7z
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/f4se/f4se_0_06_21.7z
Type = 7z
Physical Size = 598435
Headers Size = 5414
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 393
Size:       3284040
Compressed: 598435

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 712979 bytes (697 KiB)                           

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/nvse/nvse_5_1_beta4.7z
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/nvse/nvse_5_1_beta4.7z
Type = 7z
Physical Size = 712979
Headers Size = 4131
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 12
Files: 231
Size:       4902927
Compressed: 712979

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 6324906 bytes (6177 KiB)                         

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/mwse/mwse.zip
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/mwse/mwse.zip
Type = zip
Physical Size = 6324906

Everything is Ok   

Folders: 32
Files: 467
Size:       22575184
Compressed: 6324906

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 1662426 bytes (1624 KiB)                         

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/obse/obse_0021.zip
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/obse/obse_0021.zip
Type = zip
Physical Size = 1662426
Comment = ; WinRAR
; Multifunctional Integrated Archive Manager

Everything is Ok

Folders: 12
Files: 342
Size:       6092629
Compressed: 1662426
Started initial process 44880 from /usr/bin/bash -c printf '\x90\x90\x90' | dd conv=notrunc of='/home/bobby/.cache/lutris/installer/mod-organizer-2/oblivion-script-extender/obse_loader.exe' bs=1 seek=$((0x14cb))
Start monitoring process.
3+0 records in
3+0 records out
3 bytes copied, 5.1806e-05 s, 57.9 kB/s
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 624845 bytes (611 KiB)                           

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/skse/skse_1_07_03.7z
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/skse/skse_1_07_03.7z
Type = 7z
Physical Size = 624845
Headers Size = 8072
Method = LZMA2:22 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 14
Files: 544
Size:       3591799
Compressed: 624845

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 755625 bytes (738 KiB)                             

Extracting archive: /home/bobby/Downloads/MO2/mod-organizer-2/skse64/skse64_2_00_17.7z
--
Path = /home/bobby/Downloads/MO2/mod-organizer-2/skse64/skse64_2_00_17.7z
Type = 7z
Physical Size = 755625
Headers Size = 7057
Method = LZMA2:6m LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Folders: 13
Files: 520
Size:       4426059
Compressed: 755625
Started initial process 44908 from /usr/bin/bash -c # clear envs set by Lutris
export LD_LIBRARY_PATH=""

nexus_game_id=skyrimspecialedition
runner=proton

if [ ! -f "/home/bobby/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/bobby/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/bobby/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        if [ -z "$steam_library" ]; then
            steam_library=$("/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)
        fi

        if [ ! -d "$steam_library" ]; then
            "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/bobby/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/bobby/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options $game_appid '/home/bobby/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/bobby/Games/mod-organizer-2/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/bobby/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/bobby/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options '/home/bobby/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/bobby/Games/mod-organizer-2/download.sh"
        ;;
esac

if [ -d "/home/bobby/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/bobby/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/bobby/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/bobby/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/bobby/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/bobby/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Start monitoring process.
Searching for Steam in '/home/bobby/.steam/debian-installation'
Found Steam
Searching for Steam in '/home/bobby/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Steam not found in this install path
Searching for game in library '/home/bobby/.steam/debian-installation'
Searching for game in library '/home/bobby/.steam/debian-installation'
Searching for game in library '/home/bobby/Games'
Found game
Installing script extender...
Executing mkdir -p /home/bobby/Games/steamapps/compatdata/489830
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 40
drwxrwxr-x  9 bobby bobby 4096 Oct 28 12:26 .
drwxrwxr-x  4 bobby bobby 4096 Oct 28 12:22 ..
drwx------  4 bobby bobby 4096 Oct 28 12:26 java
drwxrwxr-x  4 bobby bobby 4096 Oct 28 12:15 ProgramData
drwxrwxr-x  6 bobby bobby 4096 Oct 28 12:15 Program Files
drwxrwxr-x  7 bobby bobby 4096 Oct 28 12:15 Program Files (x86)
drwxrwxr-x  4 bobby bobby 4096 Oct 28 12:15 users
drwxrwxr-x  3 bobby bobby 4096 Oct 28 12:15 vrclient
drwxrwxr-x 19 bobby bobby 4096 Oct 28 12:18 windows
-rw-r--r--  1 bobby bobby    9 Oct 28 12:15 .windows-serial

Registry info:
/home/bobby/Games/steamapps/compatdata/489830/pfx/system.reg:#arch=win64
/home/bobby/Games/steamapps/compatdata/489830/pfx/user.reg:#arch=win64
/home/bobby/Games/steamapps/compatdata/489830/pfx/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "wine: '/home/bobby/Games/steamapps/compatdata/489830/pfx' is a 64-bit installation, it cannot be used with a 32-bit wineserver." 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2021-10-28 12:26:32,356: Command exited with code 256
None

**Comment by rockerbacon** [comment] 2022-01-05 12:29
Duplicate of #259, discussion will continue there.

**Closed by rockerbacon** 2022-01-05 12:29 UTC
