### ISSUE TITLE
Launching Fallout 4 Causes Black Screen Before Main Menu

### ISSUE THREAD

**Issue by ThisNekoGuy** [rockerbacon/lutris-skyrimse-installers#135] opened 2020-08-05 22:44 UTC
For whatever reason, I can't even make it to the main menu when I try to launch the game with F4SE via MO2.

I do have a lot of mods installed, but I was careful about selecting them and made a patch for them, but this shouldn't cause a black-screen hang before even reaching the main menu.

**Comment by rockerbacon** [comment] 2020-08-06 01:28
1. Do you get the same problem when you launch it with no mods and no F4SE plugins?
2. Are you using an ENB?

**Comment by ThisNekoGuy** [comment] 2020-08-06 09:03
I looked through it and it seemed that no F4SE plugins were causing this (and I'm not using any ENBs).

I did, however, find out that the problem was that SmashPatch generated by MatorSmash (a tool that the zEdit developer created to perform BashedPatches better than WryeBash before he started making zEdit).

However, since I can't get WryeBash to run in MO2 for some reason, it was my only chance of getting a patch for my load order...
Don't know what to do :/

**Comment by rockerbacon** [comment] 2020-08-06 22:15
Since the problem is related to tools and not to the game itself I'll close this issue. There already is an issue open for WryeBash: #133

**Closed by rockerbacon** 2020-08-06 22:15 UTC
Labels: fallout4, not our bug
