### ISSUE TITLE
sha256sum mismatch on `vc_redist.x86-exe`

### ISSUE THREAD

**Issue by paulollivier** [rockerbacon/lutris-skyrimse-installers#169] opened 2020-11-08 10:15 UTC
Hi,
i'm having an error on trying to use this project, and couldn't figure out where it comes from:

```
[download...]
2020-11-07 23:42:48 (1,06 MB/s) — « vc_redist.x86.exe » sauvegardé [14284944/14284944]

Executing cd /home/paul/Games/mod-organizer-2
------------------------------------------------------
sha256sum mismatch! Rename /home/paul/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.
```

Of course, applying the suggestion of the last log line doesn't change anything, and i can reproduce the behaviour at will, with any of the two games i have installed: Fallout 4 & Skyrim SE.

Could someone point me in the right direction to change the expected checksum?
Also, which wine is used? the one from proton?

Thank you.

**Comment by rockerbacon** [comment] 2020-11-08 16:03
Duplicate of #61

**Closed by rockerbacon** 2020-11-08 16:03 UTC
